#!/bin/bash
# Wrapper — delegates to workflow-harness canonical hook
# Auto-generated by workflow-harness/setup.sh
# Harness installed at: /home/y/Workflow/workflow-harness

HOOK="/home/y/Workflow/workflow-harness/hooks/pre-tool-guard.sh"
if [ -f "$HOOK" ]; then
  exec bash "$HOOK"
fi

# Fallback: search common locations relative to project root
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
for D in "workflow-harness" ".claude/workflow-harness" "vendor/workflow-harness"; do
  F="$PROJECT_ROOT/$D/hooks/pre-tool-guard.sh"
  if [ -f "$F" ]; then
    exec bash "$F"
  fi
done

# Harness not found — allow (don't block if harness is missing)
exit 0
