#!/bin/bash
# Workflow Harness Setup — install hooks into consuming project
# Usage: bash workflow-harness/setup.sh
# (or bash <path-to-harness>/setup.sh)

set -e

# Detect harness directory (where this script lives)
HARNESS_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(pwd)"

echo "=== Workflow Harness Setup ==="
echo "Harness: $HARNESS_DIR"
echo "Project: $PROJECT_DIR"

# --- dependency bootstrap ---
install_rtk() {
  if command -v rtk >/dev/null 2>&1; then
    echo "rtk: $(rtk --version 2>/dev/null | head -1)"
    return 0
  fi

  local uname_s uname_m os_triple arch asset url tmpdir bin_dst found
  uname_s="$(uname -s 2>/dev/null || echo unknown)"
  uname_m="$(uname -m 2>/dev/null || echo unknown)"

  case "$uname_s" in
    Linux)                os_triple="unknown-linux-gnu" ;;
    Darwin)               os_triple="apple-darwin" ;;
    MINGW*|MSYS*|CYGWIN*) os_triple="pc-windows-msvc" ;;
    *) echo "[rtk] WARNING: unsupported OS $uname_s, skipping rtk install" >&2; return 1 ;;
  esac

  case "$uname_m" in
    x86_64|amd64)  arch="x86_64" ;;
    arm64|aarch64) arch="aarch64" ;;
    *) echo "[rtk] WARNING: unsupported arch $uname_m, skipping rtk install" >&2; return 1 ;;
  esac

  asset="rtk-${arch}-${os_triple}"
  url="https://github.com/rtk-ai/rtk/releases/latest/download/${asset}.zip"

  tmpdir="$(mktemp -d 2>/dev/null || mktemp -d -t rtk)"
  if [ -z "$tmpdir" ] || [ ! -d "$tmpdir" ]; then
    echo "[rtk] WARNING: mktemp failed, skipping rtk install" >&2
    return 1
  fi

  echo "Downloading rtk: $url"
  if command -v curl >/dev/null 2>&1; then
    if ! curl -fsSL "$url" -o "$tmpdir/rtk.zip"; then
      echo "[rtk] WARNING: curl download failed" >&2
      rm -rf "$tmpdir"
      return 1
    fi
  elif command -v wget >/dev/null 2>&1; then
    if ! wget -q "$url" -O "$tmpdir/rtk.zip"; then
      echo "[rtk] WARNING: wget download failed" >&2
      rm -rf "$tmpdir"
      return 1
    fi
  else
    echo "[rtk] WARNING: neither curl nor wget available" >&2
    rm -rf "$tmpdir"
    return 1
  fi

  if ! command -v unzip >/dev/null 2>&1; then
    echo "[rtk] WARNING: unzip not available" >&2
    rm -rf "$tmpdir"
    return 1
  fi

  if ! unzip -q "$tmpdir/rtk.zip" -d "$tmpdir"; then
    echo "[rtk] WARNING: unzip failed" >&2
    rm -rf "$tmpdir"
    return 1
  fi

  bin_dst="$HOME/.local/bin"
  mkdir -p "$bin_dst"

  if [ -f "$tmpdir/rtk.exe" ]; then
    mv "$tmpdir/rtk.exe" "$bin_dst/rtk.exe"
  elif [ -f "$tmpdir/rtk" ]; then
    mv "$tmpdir/rtk" "$bin_dst/rtk"
    chmod +x "$bin_dst/rtk"
  else
    found="$(find "$tmpdir" -maxdepth 3 -type f \( -name rtk -o -name rtk.exe \) 2>/dev/null | head -1)"
    if [ -n "$found" ]; then
      if [ "${found##*.}" = "exe" ]; then
        mv "$found" "$bin_dst/rtk.exe"
      else
        mv "$found" "$bin_dst/rtk"
        chmod +x "$bin_dst/rtk"
      fi
    else
      echo "[rtk] WARNING: rtk binary not found in archive" >&2
      rm -rf "$tmpdir"
      return 1
    fi
  fi

  rm -rf "$tmpdir"

  case ":$PATH:" in
    *":$bin_dst:"*) ;;
    *) echo "[rtk] WARNING: $bin_dst is not in $PATH. Add 'export PATH=\"$HOME/.local/bin:$PATH\"' to your shell rc." >&2 ;;
  esac

  echo "rtk installed to $bin_dst"
  return 0
}

check_jq() {
  if command -v jq >/dev/null 2>&1; then
    echo "jq: $(jq --version 2>/dev/null)"
    return 0
  fi

  local uname_s
  uname_s="$(uname -s 2>/dev/null || echo unknown)"
  echo "[jq] WARNING: jq is not installed. rtk-rewrite hook requires jq." >&2
  case "$uname_s" in
    Linux)                echo "  Install: sudo apt install jq  (or your package manager)" >&2 ;;
    Darwin)               echo "  Install: brew install jq" >&2 ;;
    MINGW*|MSYS*|CYGWIN*) echo "  Install: scoop install jq  (or winget install jqlang.jq)" >&2 ;;
    *)                    echo "  See: https://jqlang.github.io/jq/download/" >&2 ;;
  esac
  return 0
}

install_rtk || echo "rtk install skipped/failed (non-fatal)" >&2
check_jq
# --- end dependency bootstrap ---

# 1. Create .claude/hooks/ if needed
mkdir -p "$PROJECT_DIR/.claude/hooks"

# 2. Create pre-tool-guard wrapper
# NOTE: Unquoted EOF so $HARNESS_DIR is expanded at setup time (baked path).
#       Runtime variables use \$ to survive the heredoc expansion.
cat > "$PROJECT_DIR/.claude/hooks/pre-tool-guard.sh" << EOF
#!/bin/bash
# Wrapper — delegates to workflow-harness canonical hook
# Auto-generated by workflow-harness/setup.sh
# Harness installed at: $HARNESS_DIR

HOOK="$HARNESS_DIR/hooks/pre-tool-guard.sh"
if [ -f "\$HOOK" ]; then
  exec bash "\$HOOK"
fi

# Fallback: search common locations relative to project root
SCRIPT_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
PROJECT_ROOT="\$(cd "\$SCRIPT_DIR/../.." && pwd)"
for D in "workflow-harness" ".claude/workflow-harness" "vendor/workflow-harness"; do
  F="\$PROJECT_ROOT/\$D/hooks/pre-tool-guard.sh"
  if [ -f "\$F" ]; then
    exec bash "\$F"
  fi
done

# Harness not found — allow (don't block if harness is missing)
exit 0
EOF
chmod +x "$PROJECT_DIR/.claude/hooks/pre-tool-guard.sh"

# 3. Update .claude/settings.json
SETTINGS="$PROJECT_DIR/.claude/settings.json"

if [ ! -f "$SETTINGS" ]; then
  # Create new settings with guard hook
  mkdir -p "$PROJECT_DIR/.claude"
  cat > "$SETTINGS" << 'JSON'
{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "",
        "hooks": [{"type": "command", "command": "bash .claude/hooks/pre-tool-guard.sh"}]
      }
    ]
  }
}
JSON
  echo "Created $SETTINGS with pre-tool-guard"
else
  # Auto-add hooks to existing settings.json using node
  node -e "
const fs = require('fs');
const path = process.argv[1];
const settings = JSON.parse(fs.readFileSync(path, 'utf8'));
if (!settings.hooks) settings.hooks = {};
if (!settings.hooks.PreToolUse) settings.hooks.PreToolUse = [];

// pre-tool-guard
const guardExists = settings.hooks.PreToolUse.some(h =>
  h.hooks && h.hooks.some(hh => typeof hh === 'object' ? (hh.command && hh.command.includes('pre-tool-guard')) : (typeof hh === 'string' && hh.includes('pre-tool-guard')))
);
if (!guardExists) {
  settings.hooks.PreToolUse.push({matcher: '', hooks: [{type: 'command', command: 'bash .claude/hooks/pre-tool-guard.sh'}]});
  console.log('Added pre-tool-guard hook');
} else {
  console.log('pre-tool-guard already registered');
}

fs.writeFileSync(path, JSON.stringify(settings, null, 2) + '\n');
" "$SETTINGS"
fi

# 4. Register harness MCP server in .mcp.json
MCPJSON="$PROJECT_DIR/.mcp.json"

if [ ! -f "$MCPJSON" ]; then
  # Create new .mcp.json with harness entry
  # NOTE: Unquoted EOF so $HARNESS_DIR is expanded at setup time (baked path).
  cat > "$MCPJSON" << EOF
{
  "mcpServers": {
    "harness": {
      "command": "bash",
      "args": ["$HARNESS_DIR/mcp-server/start.sh"],
      "cwd": "$HARNESS_DIR/mcp-server",
      "env": {
        "STATE_DIR": "$HARNESS_DIR/mcp-server/.claude/state"
      }
    }
  }
}
EOF
  echo "Created $MCPJSON with harness MCP server"
else
  # Auto-add harness entry to existing .mcp.json using node
  # Skip if either "harness" or "workflow-harness" entry is already present
  # (both names point to the same server; avoid duplicate registration).
  node -e "
const fs = require('fs');
const path = process.argv[1];
const harnessDir = process.argv[2];
const mcp = JSON.parse(fs.readFileSync(path, 'utf8'));
if (!mcp.mcpServers) mcp.mcpServers = {};

if (mcp.mcpServers.harness) {
  console.log('harness MCP server already registered');
} else if (mcp.mcpServers['workflow-harness']) {
  console.log('workflow-harness MCP server already registered; skipping harness entry');
} else {
  mcp.mcpServers.harness = {
    command: 'bash',
    args: [harnessDir + '/mcp-server/start.sh'],
    cwd: harnessDir + '/mcp-server',
    env: {
      STATE_DIR: harnessDir + '/mcp-server/.claude/state'
    }
  };
  console.log('Added harness MCP server');
}

fs.writeFileSync(path, JSON.stringify(mcp, null, 2) + '\n');
" "$MCPJSON" "$HARNESS_DIR"
fi

# 5. Create .agent directory for state tracking
mkdir -p "$PROJECT_DIR/.agent"

# 6. Create default .worker-allowed-tools if not present (bootstrap fix)
if [ ! -f "$PROJECT_DIR/.agent/.worker-allowed-tools" ]; then
  echo "Read,Glob,Grep,Write,Edit,Bash" > "$PROJECT_DIR/.agent/.worker-allowed-tools"
  echo "Created .agent/.worker-allowed-tools with default tool set"
fi

# 7. Create default .worker-allowed-extensions if not present (H-2: extension enforcement)
if [ ! -f "$PROJECT_DIR/.agent/.worker-allowed-extensions" ]; then
  echo ".ts,.tsx,.js,.jsx,.py,.go,.rs,.java,.toon,.json,.yml,.yaml,.toml,.env,.sh,.md,.mdx,.mmd" > "$PROJECT_DIR/.agent/.worker-allowed-extensions"
  echo "Created .agent/.worker-allowed-extensions with permissive default"
fi

# 8. Copy skill files to target project (force overwrite for latest version)
SKILLS_SRC="$HARNESS_DIR/.claude/skills/workflow-harness"
SKILLS_DST="$PROJECT_DIR/.claude/skills/workflow-harness"

if [ -d "$SKILLS_SRC" ]; then
  mkdir -p "$SKILLS_DST"
  cp -rf "$SKILLS_SRC/"* "$SKILLS_DST/"
  echo "Copied skill files to $SKILLS_DST:"
  ls -1 "$SKILLS_DST" | sed 's/^/  /'
else
  echo "WARNING: Skills source not found: $SKILLS_SRC"
fi

# 9. Copy rule files to target project (no overwrite of existing rules)
RULES_SRC="$HARNESS_DIR/.claude/rules"
RULES_DST="$PROJECT_DIR/.claude/rules"

if [ -d "$RULES_SRC" ]; then
  mkdir -p "$RULES_DST"
  COPIED=0
  SKIPPED=0
  for f in "$RULES_SRC"/*; do
    fname="$(basename "$f")"
    if [ -f "$RULES_DST/$fname" ]; then
      SKIPPED=$((SKIPPED + 1))
      echo "  [skip] $fname (already exists)"
    else
      cp "$f" "$RULES_DST/$fname"
      COPIED=$((COPIED + 1))
      echo "  [copy] $fname"
    fi
  done
  echo "Rules: $COPIED copied, $SKIPPED skipped (existing preserved)"
else
  echo "WARNING: Rules source not found: $RULES_SRC"
fi

# 10. Copy agent definitions to target project
AGENTS_SRC="$HARNESS_DIR/.claude/agents"
AGENTS_DEST="$PROJECT_DIR/.claude/agents"
mkdir -p "$AGENTS_DEST"
for agent_file in "$AGENTS_SRC"/*.md; do
  [ -f "$agent_file" ] || continue
  fname=$(basename "$agent_file")
  cp -f "$agent_file" "$AGENTS_DEST/$fname"
  echo "  Copied: $fname"
done
echo "Agent definitions synced."

echo ""
echo "=== Setup Complete ==="
echo "2-layer per-process guard installed (orchestrator + subagent, part of 3-layer architecture)."
echo "harness MCP server registered in .mcp.json."
echo "Orchestrator/Subagent access control active."
echo "Skill files and rules synced."
