#!/bin/bash
# Workflow Harness Setup — install hooks into consuming project
# Usage: bash workflow-harness/setup.sh
# (or bash <path-to-harness>/setup.sh)

set -e

# Detect harness directory (where this script lives)
HARNESS_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(pwd)"

echo "=== Workflow Harness Setup ==="
echo "Harness: $HARNESS_DIR"
echo "Project: $PROJECT_DIR"

# 1. Create .claude/hooks/ if needed
mkdir -p "$PROJECT_DIR/.claude/hooks"

# 2. Create a thin wrapper hook that delegates to the harness hook
# This way the harness hook stays in the harness repo and updates are automatic
# NOTE: Unquoted EOF so $HARNESS_DIR is expanded at setup time (baked path).
#       Runtime variables use \$ to survive the heredoc expansion.
cat > "$PROJECT_DIR/.claude/hooks/pre-tool-3layer-guard.sh" << EOF
#!/bin/bash
# Wrapper — delegates to workflow-harness canonical hook
# Auto-generated by workflow-harness/setup.sh
# Harness installed at: $HARNESS_DIR

HOOK="$HARNESS_DIR/hooks/pre-tool-3layer-guard.sh"
if [ -f "\$HOOK" ]; then
  exec bash "\$HOOK"
fi

# Fallback: search common locations relative to project root
SCRIPT_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
PROJECT_ROOT="\$(cd "\$SCRIPT_DIR/../.." && pwd)"
for D in "workflow-harness" ".claude/workflow-harness" "vendor/workflow-harness"; do
  F="\$PROJECT_ROOT/\$D/hooks/pre-tool-3layer-guard.sh"
  if [ -f "\$F" ]; then
    exec bash "\$F"
  fi
done

# Harness not found — allow (don't block if harness is missing)
exit 0
EOF
chmod +x "$PROJECT_DIR/.claude/hooks/pre-tool-3layer-guard.sh"

# 3. Update .claude/settings.json
SETTINGS="$PROJECT_DIR/.claude/settings.json"

if [ ! -f "$SETTINGS" ]; then
  # Create new settings with 3layer guard
  mkdir -p "$PROJECT_DIR/.claude"
  cat > "$SETTINGS" << 'JSON'
{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "",
        "hooks": [{"type": "command", "command": "bash .claude/hooks/pre-tool-3layer-guard.sh"}]
      }
    ]
  }
}
JSON
  echo "Created $SETTINGS with 3-layer guard"
else
  # Check if already registered
  if grep -q "3layer-guard" "$SETTINGS"; then
    echo "3-layer guard already registered in settings.json"
  else
    echo "WARNING: $SETTINGS exists. Please manually add this PreToolUse hook entry:"
    echo '  {"matcher": "", "hooks": [{"type": "command", "command": "bash .claude/hooks/pre-tool-3layer-guard.sh"}]}'
  fi
fi

# 4. Create .agent directory for coordinator-ids tracking
mkdir -p "$PROJECT_DIR/.agent"

echo ""
echo "=== Setup Complete ==="
echo "3-layer guard installed. Orchestrator/Coordinator/Worker access control active."
